### ISSUE TITLE
Issue with the Journal Shortcut

### ISSUE THREAD

**Issue by jaidenthebear** [lensvol/fl-small-mercies#14]
When the option "Replace the usual 'Share snippet' button with a quicker alternative." is enabled I appear to be getting the original storylet journaled each time rather than the sub one that I clicked on. For example on "Comparing Notes with the Youthful Naturalist" if I choose to "Discuss Hunter's Keep" and attempt to journal this snippet it will still journal the text for "Comparing Notes with the Youthful Naturalist." This unfortunately caused me to miss out on adding a large section of evolution to my journal as I hadn't noticed until afterwards.
Journaling works fine when that option is disabled.
If this is a mistake on my part or there's anything extra I can provide I'd be happy to help

![image](https://github.com/lensvol/fl-small-mercies/assets/157239237/15c8f2bb-2308-4a4b-9c37-0db787ff86e4)

![image](https://github.com/lensvol/fl-small-mercies/assets/157239237/afa9ee0d-e28e-4d43-8b2a-9b93a30789e3)

![image](https://github.com/lensvol/fl-small-mercies/assets/157239237/51439659-ef0f-4544-b2ea-e50de9197d0b)

**Comment by lensvol** [comment]
Yes, unfortunately there was a problem in the release 3.0.1

It had since been fixed in 3.0.3 which already rolled out to Mozilla Add-On Store. Chrome Web Store is still reviewing 3.0.2, so it may take at least a day more to get 3.0.3 deployed there as well 😔 

If you cannot wait this long but still want to use that feature then please try install directly from the GitHub.

We apologize for the inconvenience :(
